/*
 * botPanel.java
 *
 * Created on February 22, 2007, 10:15 PM
 */

package eu.somatik.botleecher;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;
import javax.swing.Timer;
import org.jibble.pircbot.User;

/**
 *
 * @author  francisdb
 */
public class BotPanel extends javax.swing.JPanel {
    
    private final User user;
    private final BotMediator mediator;
    private Timer updater;
    
    /** Creates new form botPanel
     * @param mediator
     * @param user
     */
    public BotPanel(final BotMediator mediator, final User user) {
        initComponents();
        this.user = user;
        this.mediator = mediator;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        botScrollPane = new javax.swing.JScrollPane();
        botTextPane = new javax.swing.JTextPane();
        packSpinner = new javax.swing.JSpinner();
        startButton = new javax.swing.JButton();
        transferStatusBar = new javax.swing.JProgressBar();

        botScrollPane.setViewportView(botTextPane);

        packSpinner.setValue(1);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(packSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(transferStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(packSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
    startButton.setEnabled(false);
    mediator.start(user, (Integer)packSpinner.getValue());
    updater = new Timer(500, new UpdateListerner());
    updater.setCoalesce(true);
    updater.start();
}//GEN-LAST:event_startButtonActionPerformed

    private class UpdateListerner implements ActionListener {
        private final NumberFormat formatter;

        public UpdateListerner() {
            formatter = NumberFormat.getInstance();
            formatter.setMaximumFractionDigits(0);
        }

        public void actionPerformed(ActionEvent e) {
            IrcConnection botLeecher = mediator.getIcrConnection();
            if (botLeecher.getCurrentTransfer() != null) {
                packSpinner.setValue(new Integer(botLeecher.getCounter()));
                transferStatusBar.setMaximum((int) botLeecher.getCurrentTransfer()
                                                      .getSize());
                transferStatusBar.setValue((int) botLeecher.getCurrentTransfer()
                                                    .getProgress());
                transferStatusBar.setString((int) botLeecher.getCurrentTransfer()
                                                     .getProgressPercentage() +
                    " %");
                botTextPane.setText(botLeecher.getCurrentTransfer().getFile().getName() +
                    "\n" +
                    (int) (botLeecher.getCurrentTransfer().getTransferRate() / 1024) +
                    "Kbps \n" + "Last notice: " +
                    botLeecher.getLastMessage());

                String percentage = formatter.format(botLeecher.getCurrentTransfer()
                                                               .getProgressPercentage());
//                setTitle(percentage + "% " +
//                    botLeecher.getCurrentTransfer().getFile().getName());
            } else {
                transferStatusBar.setValue(0);
                botTextPane.setText("no transfer");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane botScrollPane;
    private javax.swing.JTextPane botTextPane;
    private javax.swing.JSpinner packSpinner;
    private javax.swing.JButton startButton;
    private javax.swing.JProgressBar transferStatusBar;
    // End of variables declaration//GEN-END:variables
    
}
